name: Run Tests

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-latest
    
    strategy:
      matrix:
        xcode: ['16.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show Swift version
      run: swift --version
      
    - name: Run tests
      run: swift test
      
    - name: Run tests with verbose output
      run: swift test --verbose
      if: failure()
      
  test-linux:
    name: Run Tests (Linux)
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
        
    - name: Show Swift version
      run: swift --version
      
    - name: Run tests
      run: swift test
      
    - name: Run tests with verbose output
      run: swift test --verbose
      if: failure() 