name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15-xlarge
    
    strategy:
      matrix:
        xcode: ['16.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show current version of Xcode
      run: /usr/bin/xcodebuild -version

    - name: Show Swift version
      run: swift --version

    - name: Enable github dependencies (SPM)
      run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
    
    - name: Run tests
      run: swift test
      
    - name: Run tests with verbose output
      run: swift test --verbose
      if: failure()